apiVersion: v1
kind: Service
metadata:
  name: dealership-service
spec:
  selector:
    app: dealership # Matches the labels of your Deployment pods
  ports:
    - protocol: TCP
      port: 80 # The port the Service exposes
      targetPort: 8000 # The port your application runs on inside the pod
  type: LoadBalancer # Requests a public IP from your cloud provider